//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodUretici.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KodUretici.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Text boyutu &quot;Ctrl+MouseTopu&quot; kullanarak ayarlanabilir.
        ///// F5 tusu ile direkt kod uretilebilir.
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///
        ///@var1 (@tr@ttip @tvar,@tr)
        ///{
        ///@tr	this.@tvar = @tvar;
        ///@tr
        ///}
        ///
        ///
        ///public class @var1
        ///{   
        ///@tr    public @ttip @tvar { get; set; }
        ///@tr
        ///}
        ///
        ////* ---- Komutlar ---- */
        ///@tr, @tr        //Tekrar ettirir
        ///@var1, @tip1    // Sabit degiskenler
        ///@kvar1, @ktip1  //Sabit degiskenlerin kucuk yazilisi
        ///@tvar, @ttip    //Tekrarli degiskenler
        ///@ktvar, @kttip   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string merhaba {
            get {
                return ResourceManager.GetString("merhaba", resourceCulture);
            }
        }
    }
}
